### ISSUE TITLE
Version errors

### ISSUE THREAD

**Issue by a-martynovich** [WoTTsecurity/agent#124]
*Subtask of #96*

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: wott-agent 0.1.5.0-7d20ed2 (/usr/lib/python3/dist-packages) is not JSON serializable

pi@raspberrypi:~ $ sudo dpkg -l | grep agent
ii  wott-agent                      0.1.5.284~7d20ed2            all          Let's Encrypt for IoT (with more bells and whistles).

```

* Build number didn't get included into the Python version. Probably because debhelper ignores all env vars and needs them to be specified manually. Also, the tilde character transformed into dash. The deb version is fine.
* The error which caused the traceback can be fixed by simply using `str(__version__)`.

**Comment by vpetersson** [comment]
@a-martynovich this should be re-opened, right? Looks like the merge of #122 closed it.

**Comment by a-martynovich** [comment]
@vpetersson This was totally intended.
