### ISSUE TITLE
Installation failure (iptables related)

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#149]
Steps to reproduce:

 * Install a brand new Raspbian Lite device
 * Install the agent
 * Run `wott-agent`

```
pi@wott-al:~ $ sudo wott-agent
Traceback (most recent call last):
  File "/usr/bin/wott-agent", line 11, in <module>
    load_entry_point('wott-agent===0.1.5.332-79491bd', 'console_scripts', 'wott-agent')()
  File "/usr/lib/python3/dist-packages/agent/__main__.py", line 47, in main
    run(ping=True, debug=args.debug, dev=args.dev)
  File "/usr/lib/python3/dist-packages/agent/__init__.py", line 565, in run
    send_ping(debug=debug, dev=dev)
  File "/usr/lib/python3/dist-packages/agent/__init__.py", line 291, in send_ping
    security_helper.block_ports(blocklist.get('block_ports', {'tcp': [], 'udp': []}))
  File "/usr/lib/python3/dist-packages/agent/security_helper.py", line 213, in block_ports
    prepare_iptables(False)
  File "/usr/lib/python3/dist-packages/agent/security_helper.py", line 168, in prepare_iptables
    if not iptc_helper.has_chain(TABLE, DROP_CHAIN, ipv6=ipv6):
  File "/usr/lib/python3/dist-packages/agent/iptc_helper.py", line 59, in has_chain
    return _iptc_gettable(table, ipv6).is_chain(chain)
  File "/usr/lib/python3/dist-packages/agent/iptc_helper.py", line 414, in _iptc_gettable
    iptc_table = Table6(table) if ipv6 else Table(table)
  File "/usr/lib/python3/dist-packages/iptc/ip4tc.py", line 1531, in __new__
    obj._init(name, autocommit)
  File "/usr/lib/python3/dist-packages/iptc/ip4tc.py", line 1547, in _init
    self.refresh()
  File "/usr/lib/python3/dist-packages/iptc/ip4tc.py", line 1584, in refresh
    self.strerror()))
iptc.ip4tc.IPTCError: can't initialize filter: b'Table does not exist (do you need to insmod?)'
```

**Comment by vpetersson** [comment]
Rebooting the device appears to solve the problem, but that's not the proper solution.

**Comment by a-martynovich** [comment]
@vpetersson can you confirm that it **always** happens?
To me it looks like iptables (netfilter) kernel module is either not loaded yet or wasn't loaded because of kernel upgrade. The latter is a normal situation (happens to everyone) and we can't do anything about it.

**Comment by vpetersson** [comment]
I can't confirm if it *always* happens, but I can confirm that it happened just now. Don't have the bandwidth today to reproduce this.

**Comment by a-martynovich** [comment]
We can't do anything if iptables kernel module is not loaded. Even if we try loading it ourselves it will most probably fail. Rebooting is the only option.

**Comment by vpetersson** [comment]
Well, then we should have error handling for that and suggest an action.
