### ISSUE TITLE
Fix firewall issue

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#219]
How to reproduce:

 * Install Raspbian Stretch
 * Set the firewall policy to "Block by default" and enable SSH
 * Save settings
 * Run `wott-agent` and you'll get the error below.

```
$ sudo wott-agent
start in ping mode...
Error while updating iptables: can't commit: b'No chain/target/match by that name'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/agent/iptables_helper.py", line 157, in block
    block_ports(False, blocklist.get('allow_ports', []))
  File "/usr/lib/python3/dist-packages/agent/iptables_helper.py", line 131, in block_ports
    add_rules(TABLE, INPUT_CHAIN, rules)
  File "/usr/lib/python3/dist-packages/agent/iptables_helper.py", line 107, in add_rules
    iptc_helper.batch_add_rules(table, rules_ipv, chain=chain, ipv6=ipv6)
  File "/usr/lib/python3/dist-packages/agent/iptc_helper.py", line 322, in batch_add_rules
    _batch_end_table(table, ipv6)
  File "/usr/lib/python3/dist-packages/agent/iptc_helper.py", line 492, in _batch_end_table
    iptc_table = _iptc_gettable(table, ipv6)
  File "/usr/lib/python3/dist-packages/agent/iptc_helper.py", line 424, in _iptc_gettable
    iptc_table.commit()
  File "/usr/lib/python3/dist-packages/iptc/ip4tc.py", line 1561, in commit
    raise IPTCError("can't commit: %s" % (self.strerror()))
iptc.ip4tc.IPTCError: can't commit: b'No chain/target/match by that name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wott-agent", line 11, in <module>
    load_entry_point('wott-agent===0.1.5.582-e908c4d', 'console_scripts', 'wott-agent')()
  File "/usr/lib/python3/dist-packages/agent/__main__.py", line 56, in main
    run(ping=True, dev=args.dev)
  File "/usr/lib/python3/dist-packages/agent/__init__.py", line 742, in run
    send_ping(dev=dev)
  File "/usr/lib/python3/dist-packages/agent/__init__.py", line 409, in send_ping
    iptables_helper.block(blocklist)
  File "/usr/lib/python3/dist-packages/agent/iptables_helper.py", line 163, in block
    logger.debug(exc_info=True)
TypeError: debug() missing 1 required positional argument: 'msg'
```

**Comment by vpetersson** [comment]
Was caused by kernel upgrade.
