### ISSUE TITLE
Fix missing dependency

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/agent#84]
I got the following error upon just installing the agent on a new device:
```
$ sudo apt-get install wott-agent
[...]
Selecting previously unselected package python3-urllib3.
Preparing to unpack .../06-python3-urllib3_1.19.1-1_all.deb ...
Unpacking python3-urllib3 (1.19.1-1) ...
Selecting previously unselected package python3-requests.
Preparing to unpack .../07-python3-requests_2.12.4-1_all.deb ...
Unpacking python3-requests (2.12.4-1) ...
Selecting previously unselected package python3-sh.
Preparing to unpack .../08-python3-sh_1.11-1_all.deb ...
Unpacking python3-sh (1.11-1) ...
Selecting previously unselected package python3-tz.
Preparing to unpack .../09-python3-tz_2016.7-0.3_all.deb ...
Unpacking python3-tz (2016.7-0.3) ...
Selecting previously unselected package ghostunnel.
Preparing to unpack .../10-ghostunnel_1.4.0+nmu2_armhf.deb ...
Unpacking ghostunnel (1.4.0+nmu2) ...
Selecting previously unselected package wott-agent.
Preparing to unpack .../11-wott-agent_0.1.4.5_all.deb ...
Unpacking wott-agent (0.1.4.5) ...
Setting up python3-sh (1.11-1) ...
Setting up python3-iptables (0.11.0-4) ...
Setting up python3-certifi (2016.2.28-1) ...
Setting up python3-psutil (5.0.1-1) ...
Setting up python3-netifaces (0.10.4-0.1+b1) ...
Setting up python3-chardet (2.3.0-2) ...
Setting up ghostunnel (1.4.0+nmu2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up python3-openssl (16.2.0-1) ...
Setting up python3-urllib3 (1.19.1-1) ...
Setting up python3-tz (2016.7-0.3) ...
Setting up python3-requests (2.12.4-1) ...
Setting up wott-agent (0.1.4.5) ...
Created symlink /etc/systemd/system/timers.target.wants/wott-agent.timer → /lib/systemd/system/wott-agent.timer.
wott-agent.service is a disabled or a static unit, not starting it.
Traceback (most recent call last):
  File "/usr/bin/wott-agent", line 11, in <module>
    load_entry_point('wott-agent==0.1.2', 'console_scripts', 'wott-agent')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/agent/__init__.py", line 10, in <module>
    from agent import journal_helper
  File "/usr/lib/python3/dist-packages/agent/journal_helper.py", line 1, in <module>
    from systemd import journal
ImportError: No module named 'systemd'
Traceback (most recent call last):
  File "/usr/bin/wott-agent", line 11, in <module>
    load_entry_point('wott-agent==0.1.2', 'console_scripts', 'wott-agent')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/agent/__init__.py", line 10, in <module>
    from agent import journal_helper
  File "/usr/lib/python3/dist-packages/agent/journal_helper.py", line 1, in <module>
    from systemd import journal
ImportError: No module named 'systemd'

Good job installing the wott-agent and welcome to the community of security conscious hardware devs!

You're one step closer to building a secure device. Your device's unique ID is:

To unleash the value of WoTT, and to gain insight into the security of your device(s), connect your device at https://dash.wott.io.

You can claim your device in the dashboard by visiting:

For more information on how to get started, visit wott.io/getting-started or drop us a line at hey@wott.io.

Regards,
The WoTT Team
```

**Comment by a-martynovich** [comment]
The reason why this happens is because debhelper build system is supposed to find the matching deb packages for all our dependencies in requirements.txt, but it fails to do so for some packages, namely psutil, systemd-python and python-iptables. So I have to add them to deb dependencies manually.
I should probably just add all packages manually to be sure.
